---
# yaml-language-server: $schema=https://blue-build.org
name: zatvor-os
description: Лучший дистрибутив которая основана на Arch Linux!

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: 40

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - xanmod-kernel-edge
      - mangohud
      - aircrack-ng
      - fastfetch
      - git
    remove:
      - firefox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.valvesoftware.Steam
          - org.mozilla.firefox
          - io.github.shifteight.Bottles
          - com.discordapp.Discord

  - type: signing
