---
# yaml-language-server: $schema=https://blue-build.org
name: zatvor-os
description: Arch Linux-ка олоҕурбут, АК-74 ытыалыыр уонна Стимнаах система!

base-image: ghcr.io/cachyos/cachyos-v3
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - xanmod-kernel-edge
      - plymouth
      - mangohud
      - aircrack-ng
      - fastfetch
      - git
    remove:
      - firefox

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.valvesoftware.Steam        # СТИМ МАННА БААР! 🎮
          - org.mozilla.firefox
          - io.github.shifteight.Bottles   # Windows оонньууларыгар анаан
          - com.discordapp.Discord         # Доҕотторгун кытта кэпсэтэргэ

  - type: signing
